### ISSUE TITLE
Suggestion#2 Add a message when player kill another player or mob

### ISSUE THREAD

**Issue by maxlehot1234** [FlareReturns/BountifulEvents#2]
Is it possible to add a title/message/actionbar message when a player kill another player and mobs.
You can add an option for killstreaks too. So if the player kill 5-10-50-100-500 players/mobs in a row, he can receive a special message for example

**Comment by FlareReturns** [comment]
Yes! It is possibile. The Kills for Mob/Players will be in 1.3.0 and the Killstreak in 1.4.0. Thanks for your suggestion. In the next Time, please create 1 Issue for the 3 Suggestion
