### ISSUE TITLE
Suggestion#3 Add a message when the player rankup

### ISSUE THREAD

**Issue by maxlehot1234** [FlareReturns/BountifulEvents#3]
Is it possible to add a message when the player rankup? I use ezrankslite to manage my server ranks and PEX for my server permissions.

So for example, if the player was at rank A and rankup to B he can see this as title:

Title:  &6You just rankup to <rankname>
Subtitle:   &6You can go at &9/warp B &6now

**Comment by FlareReturns** [comment]
As EZRanksLite has an API, i will implement it. I think in an Addon, but im not sure. Will be added in 1.5.0 (as Addon with Addon API) or directly in the Plugin. Thanks for your suggestion. Next time please create 1 Issue for the 3 Suggestions.

**Comment by FlareReturns** [comment]
Ok, looked into it. Will be added in 1.4.0. Just found out that EZRanksLite has a **RankupEvent**.
